### ISSUE TITLE
Enable the option to select a person by department. 

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#107]
In previous versions of the application, there was the option to select a person related to the department

![department](https://user-images.githubusercontent.com/97203617/207666501-bb5bc0f9-daeb-4eb0-ab3e-b200c7572f44.png)
![department-gif](https://user-images.githubusercontent.com/97203617/207666586-937045e7-6584-4fbb-8012-07260786e0dd.gif)

These are the fields in the database: 
-- Questions table ---
`assigned_department` : to save the departament. 
`assigned_to_employee_id`: to save the employee related with the deparment. 

The table with the relationship between the employee and the deparment is `EmployeesDepartments`

This option will be optional and this is to enable to create an anonymous question. 
- [ ] Disable the option of ask anonymously if the user not select an employee.

Context: 
The anonymous questions will be allowed it, but just if the user selects a specific person by department. 
The anonymous questions will not be visible in the home page. 

Ticket related with the anonymous questions. #108

**Comment by GeorginaFraire** [comment]
This option will be optional and this is to enable to create an anonymous question. 

Context: 
The anonymous questions will be allowed it, but just if the person selects a specific person and the anonymous questions will not be visible in the home page. 

Ticket related with the anonymous questions. #108

**Comment by Carlos-Reyna** [comment]
![Image](https://user-images.githubusercontent.com/97201781/208138578-d3beba35-7f55-4779-a20d-ca2e1dd7c128.png)

Hello, I worked on the front end of this feature, I did major changes to the components since we would have 3 similar components doing the same thing. 

I want to ask if the components should  have interactions between them? Like when you select a department, only then you can select an employee for example. Or if you select a location something else should happen with the employee or department  dropdown?

**Comment by GeorginaFraire** [comment]
Fixed: #140
