### ISSUE TITLE
BUG: Go back to the login page even when the user is logged 

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#117]
https://user-images.githubusercontent.com/97203617/205137075-f83cdfb1-750a-441b-b348-3e5c51048c68.mov

**Comment by albertcastaned** [comment]
Can't seem to find a way to fix this, I think it's mostly an auth0.com issue that we would need help with from IT. So that for example https://wizeline.auth0.com/u/login?state=hKFo2SBXZ1ZoQng2ZnFpa1FRV1RndWxpVGtzVFFydDRYV1VNMaFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIE1IV1E4cWtMbUEtZGNNQmJuVzVJZW54Qm5XSjVqajFTo2NpZNkgNUtuNXlsMWpRdjJjaFVzRFRHNDNvT1ZIeUlWRGtDY0k redirects to another page

**Comment by albertcastaned** [comment]
Solved without PR from AUTH0 configuration modifications
