### ISSUE TITLE
Show in the HomePage only public questions. 

### ISSUE THREAD

**Issue by GeorginaFraire** [wizeline/wize-q-remix#166]
Change the query to get the questions in the homepage (and search) to include the public questions (`is_public`, `true`)

**Comment by Carlos-Reyna** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/97201781/213299014-5ffaf043-3a16-4e74-8065-238325b7ad55.png">
@GeorginaFraire , @jackbravo. 

At the time this function fulfills the purpose of this because, admin users do not need any condition at all and a normal user will always see only enabled and public questions. Maybe the thing we didn't consider was a filter in the homepage for public questions only visible to admins? Then a condition to have "is_public: false" would make sense 🤔.
